databases:
  - name: private-events
    databaseName: private-events 
    user: private-events 
    plan: free

services:
  - type: web 
    name: private-events 
    runtime: ruby 
    plan: free 
    buildCommand: "-/bin/render-build.sh"
# preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server" 
    envVars:
      - key: DATABASE_URL 
        fromDatabase:
          name: private-events
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false- key: WEB_CONCURRENCY
        value: 2 # sensible default