default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: volodymyrpivtoranis
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: private_events_development

test:
  <<: *default
  database: private_events_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: private_events_production
